name: Deploy to AWS CodeArtifact with Pipenv

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies with Pipenv
      run: |
        pipenv install --dev

    - name: Build package with dynamic version
      run: |
        pipenv run python setup.py sdist bdist_wheel

    - name: List dist directory
      run: |
        ls -la dist/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Authenticate to AWS CodeArtifact
      id: login-codeartifact
      run: |
        TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.AWS_CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_CODEARTIFACT_DOMAIN_OWNER }} --query authorizationToken --output text)
        echo "::add-mask::$TOKEN"
        echo "TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Install Twine
      run: |
        pipenv install twine

    - name: Upload packages to CodeArtifact
      run: |
        for file in dist/*; do
          pipenv run twine upload --verbose --repository-url "https://${{ secrets.AWS_CODEARTIFACT_DOMAIN }}-${{ secrets.AWS_CODEARTIFACT_DOMAIN_OWNER }}.d.codeartifact.us-east-2.amazonaws.com/pypi/${{ secrets.AWS_CODEARTIFACT_REPOSITORY }}/" --username aws --password "${{ env.TOKEN }}" "$file"
        done
